START TRANSACTION;
CREATE TABLE IF NOT EXISTS `chats` (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL,
    initial_message_id TEXT NOT NULL,
    status VARCHAR(6) NOT NULL,
    
)